M48
; DRILL file KiCad 10.0.1-10.0.1~ubuntu22.04.1 date 2026-07-17T13:41:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-17T13:41:13+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1-10.0.1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X87.0Y-94.0
X87.0Y-129.0
X154.0Y-94.0
X154.0Y-129.0
M30
